version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-jobportal
    restart: always
    environment:
      POSTGRES_USER: jp1234
      POSTGRES_PASSWORD: PORTaLDb1903
      POSTGRES_DB: JobPortalDB
    ports:
      - "5434:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
